### ISSUE TITLE
readMessagePayload may return (nil, nil)

### ISSUE THREAD

**Issue by urey-hiker** [ossrs/go-oryx-lib#8]
```
	// Got entire RTMP message?
	if int(chunk.message.payloadLength) == len(chunk.message.Payload) {
		m = chunk.message
		chunk.message = nil
	}

	return
```
When we did not got the entire RTMP message, readMessagePayload will return (nil, nil). 
which cause `onMessageArrivated` got a nil message.
```
		if m, err = v.readMessagePayload(chunk); err != nil {
			return
		}

		if err = v.onMessageArrivated(m); err != nil {
			return
		}
```

May I create a new error variable? `var errTryAgain = errors.New("Try again")`

**Comment by winlinvip** [comment]
If we use system error, it seems ok to use errTryAgain. But if we use `go-oryx-lib/errors` to return and generate error, maybe it's not so good enough, because it will generate error with callstack, right?

So, I think it's ok to return `nil,nil` and we just need to add a comment to the API for this special situation.

**Comment by winlinvip** [comment]
I use complex errors(`go-oryx-lib/errors`) in RTMP, please read cba071e09780d92d5056909765935f9ca860fd9b

**Comment by urey-hiker** [comment]
OK, I will check complex errors.

The return of `nil, nil` will `onMessageArrivated` ran into panic.

`v.onMessageArrivated(m *Message)->v.DecodeMessage(m *Message)->p := m.Payload[:]`

**Comment by winlinvip** [comment]
Please file a PR to fix the panic.
